In [5]:
words = open("names.txt" , 'r').read().splitlines()


In [6]:
import math
import numpy as np 
import matplotlib.pyplot as plt
from graphviz import Digraph


In [7]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i , s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s , i in stoi.items()}


In [8]:
import torch
N = torch.zeros((27,27) ,dtype=torch.int32)
N # here its an [28*28] matrix

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],


In [9]:

for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1 , ch2 in zip(chs ,chs[1:]):
        id1 , id2 = stoi[ch1] ,stoi[ch2]
        N[id1 ,id2] += 1 # here like [0,0] += 1



In [10]:
probabilites = torch.zeros((27,27))
for i in range(27):
    totalSum = N[i].sum()

    for j in range(27):
        val = N[i][j]
        prob = val / totalSum
        probabilites[i][j] = prob


In [35]:
ix = 1
print(probabilites[ix])
while True:
    p = probabilites[ix]
    # print(p)
    print(itos[ix], end='')

    ix = torch.multinomial(p, num_samples=1).item()
    # print(ix)

    if ix == 0:
        break



tensor([0.1960, 0.0164, 0.0160, 0.0139, 0.0308, 0.0204, 0.0040, 0.0050, 0.0688,
        0.0487, 0.0052, 0.0168, 0.0746, 0.0482, 0.1605, 0.0019, 0.0024, 0.0018,
        0.0963, 0.0330, 0.0203, 0.0112, 0.0246, 0.0048, 0.0054, 0.0605, 0.0128])
a

In [14]:
p = torch.tensor([0.1, 0.07, 0.2])

torch.multinomial(p, 1)

tensor([2])